language: node_js

node_js:
  - "6.9"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

env:
    - MONGO_URL=mongodb://127.0.0.1/travis

script: "npm run-script test-ci"

after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
