version: '2'

services:
  # MongoDB container
  db:
    image: mongo:3
    ports:
      - "27017:27017"

  # App container
  app:
    build: ./docker
    links:
      - db
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://db/db
    ports:
      - "${APP_PORT}3000"
    env_file: .env
