version: '2'

services:
  # MongoDB container
  db: 
    image: mongo:3

  # App container
  app:
    build: .
    links:
      - db
    environment:
      PORT: 3000
      MONGO_URL: mongodb://db/db
    ports:
      - "3000:3000"
    env_file: .env
